spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: ENC(HA3sz/nrsJJiE81Pl0+MYg==)
    password: ENC(QXNGz8mcpr7AJCVpXj4jyeZbsV1ozq1V)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

